#Created by webjeda - http://webjeda.com

title: BZ FurFur 
email: shop@bzfurfur.com


baseurl: /bzfurfur

sass:
 style: compressed
 
 
# Tracker
analytics: UA-83979019-1
 
### exclude the instructions / write-up in the README.md
exclude:
- README.md
